platform :ios,'9.0'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bracelet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bracelet
  use_frameworks!
  pod 'iOSDFULibrary', '~>3.0.3'
  pod 'AFNetworking'
  pod 'BMKLocationKit'

end
